routes/web.php
            Route::post('update-estado', ['as' => 'admin.paquetes.update-estado', 'uses' => 'PaquetesController@updateEstado']);
            Route::post('change-user-paquete', ['as' => 'admin.paquetes.change-user-paquete', 'uses' => 'PaquetesController@changeUserPaquete']);
            Route::get('editar/{id}', ['as' => 'admin.paquetes.edit', 'uses' => 'PaquetesController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.paquetes.update', 'uses' => 'PaquetesController@update']);
            Route::get('eliminar/{id}', ['as' => 'admin.paquetes.delete', 'uses' => 'PaquetesController@delete']);
            Route::get('buscar-ajax', ['as' => 'admin.paquetes.buscar-ajax', 'uses' => 'PaquetesController@buscarAjax']);
            Route::get('buscar-ajax-multi', ['as' => 'admin.paquetes.buscar-ajax-multi', 'uses' => 'PaquetesController@buscarAjaxMulti']);
            Route::get('actualizar-estado', ['as' => 'admin.paquetes.form-cambio-estado', 'uses' => 'PaquetesController@formCambioEstado']);
            Route::get('actualizar-estado-test', ['as' => 'admin.paquetes.form-cambio-estado-test', 'uses' => 'PaquetesController@formCambioEstadoTest']);
            Route::post('actualizar-estado', ['as' => 'admin.paquetes.cambio-estado', 'uses' => 'PaquetesController@cambioEstado']);
            Route::get('packlist', ['as' => 'admin.paquetes.find-packlist', 'uses' => 'PaquetesController@findPacklist']);
            Route::get('generar-etiquetas/{id}', ['as' => 'admin.paquetes.generar-etiquetas', 'uses' => 'PaquetesController@generarEtiquetas']);
            Route::get('dias', ['as' => 'admin.paquetes.dias', 'uses' => 'DiasController@dias']);
        });

        Route::group(['prefix' => 'pagos'], function() {
            Route::get('/', ['as' => 'admin.pagos.index', 'uses' => 'PagosController@index']);
            Route::get('procesar/{pago}', ['as' => 'admin.pagos.procesar', 'uses' => 'PagosController@procesar']);
        });

        Route::group(['prefix' => 'message'], function() {
            Route::get('/', ['as' => 'admin.messages.index', 'uses' => 'MessageController@index']);
            Route::post('/', ['as' => 'admin.messages.submit', 'uses' => 'MessageController@submit']);
        });

        Route::group(['prefix' => 'invoices'], function() {
            Route::get('/', ['as' => 'admin.invoices.index', 'uses' => 'InvoicesController@index']);
            Route::get('registrar', ['as' => 'admin.invoices.create', 'uses' => 'InvoicesController@create']);
            Route::post('registrar', ['as' => 'admin.invoices.store', 'uses' => 'InvoicesController@store']);
            Route::post('join', ['as' => 'admin.invoices.join', 'uses' => 'InvoicesController@join']);
            Route::get('{id}', ['as' => 'admin.invoices.show', 'uses' => 'InvoicesController@show']);
            Route::get('{id}/pago', ['as' => 'admin.invoices.pago', 'uses' => 'InvoicesController@pago']);
            Route::get('{id}/hide', ['as' => 'admin.invoices.hide', 'uses' => 'InvoicesController@hide']);
            Route::get('{id}/send-email', ['as' => 'admin.invoices.email', 'uses' => 'InvoicesController@email']);
            Route::post('{id}/payment-amount', ['as' => 'admin.invoices.pay-amount', 'uses' => 'InvoicesController@payAmount']);
        });


        Route::get('invoice-manual/get-user-data', ['as' => 'admin.invoice-manual.get-user-data', 'uses' => 'InvoiceManualController@getUserData']);
        // Route::resource('invoice-manual', 'InvoiceManualController');
        Route::get('invoice-manual', ['as' => 'admin.invoice-manual.index', 'uses' => 'InvoiceManualController@index']);
        Route::get('invoice-manual/create', ['as' => 'admin.invoice-manual.create', 'uses' => 'InvoiceManualController@create']);
        Route::post('invoice-manual/store', ['as' => 'admin.invoice-manual.store', 'uses' => 'InvoiceManualController@store']);
        Route::get('invoice-manual/{id}/print-view', ['as' => 'admin.invoice-manual.print-view', 'uses' => 'InvoiceManualController@printView']);

        Route::group(['prefix' => 'empresas'], function() {
            Route::get('/', ['as' => 'admin.empresas.index', 'uses' => 'EmpresasController@index']);
            Route::get('registrar', ['as' => 'admin.empresas.create', 'uses' => 'EmpresasController@create']);
            Route::post('registrar', ['as' => 'admin.empresas.store', 'uses' => 'EmpresasController@store']);
            Route::get('editar/{id}', ['as' => 'admin.empresas.edit', 'uses' => 'EmpresasController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.empresas.update', 'uses' => 'EmpresasController@update']);
            Route::get('eliminar/{id}', ['as' => 'admin.empresas.delete', 'uses' => 'EmpresasController@delete']);
        });

        Route::group(['prefix' => 'sucursales'], function() {
            Route::get('/', ['as' => 'admin.sucursales.index', 'uses' => 'SucursalesController@index']);
            Route::get('registrar', ['as' => 'admin.sucursales.create', 'uses' => 'SucursalesController@create']);
            Route::post('registrar', ['as' => 'admin.sucursales.store', 'uses' => 'SucursalesController@store']);
            Route::get('editar/{id}', ['as' => 'admin.sucursales.edit', 'uses' => 'SucursalesController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.sucursales.update', 'uses' => 'SucursalesController@update']);
            Route::get('eliminar/{id}', ['as' => 'admin.sucursales.delete', 'uses' => 'SucursalesController@delete']);
        });

        Route::group(['prefix' => 'preguntas'], function() {
            Route::get('/', ['as' => 'admin.preguntas.index', 'uses' => 'PreguntasController@index']);
            Route::get('registrar', ['as' => 'admin.preguntas.create', 'uses' => 'PreguntasController@create']);
            Route::post('registrar', ['as' => 'admin.preguntas.store', 'uses' => 'PreguntasController@store']);
            Route::post('reordenar', ['as' => 'admin.preguntas.reordenar', 'uses' => 'PreguntasController@reordenar']);
            Route::get('editar/{id}', ['as' => 'admin.preguntas.edit', 'uses' => 'PreguntasController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.preguntas.update', 'uses' => 'PreguntasController@update']);
            Route::get('eliminar/{id}', ['as' => 'admin.preguntas.delete', 'uses' => 'PreguntasController@delete']);
        });

        Route::group(['prefix' => 'marcas'], function() {
            Route::get('/', ['as' => 'admin.marcas.index', 'uses' => 'MarcasController@index']);
            Route::get('registrar', ['as' => 'admin.marcas.create', 'uses' => 'MarcasController@create']);
            Route::post('registrar', ['as' => 'admin.marcas.store', 'uses' => 'MarcasController@store']);
            Route::get('editar/{id}', ['as' => 'admin.marcas.edit', 'uses' => 'MarcasController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.marcas.update', 'uses' => 'MarcasController@update']);
            Route::get('eliminar/{id}', ['as' => 'admin.marcas.delete', 'uses' => 'MarcasController@delete']);
        });

        Route::group(['prefix' => 'modelos'], function() {
            Route::get('/', ['as' => 'admin.modelos.index', 'uses' => 'ModelosController@index']);
            Route::get('registrar', ['as' => 'admin.modelos.create', 'uses' => 'ModelosController@create']);
            Route::post('registrar', ['as' => 'admin.modelos.store', 'uses' => 'ModelosController@store']);
            Route::get('editar/{id}', ['as' => 'admin.modelos.edit', 'uses' => 'ModelosController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.modelos.update', 'uses' => 'ModelosController@update']);
            Route::get('eliminar/{id}', ['as' => 'admin.modelos.delete', 'uses' => 'ModelosController@delete']);
        });

        Route::group(['prefix' => 'productos'], function() {
            Route::get('/', ['as' => 'admin.productos.index', 'uses' => 'ProductosController@index']);
            Route::get('registrar', ['as' => 'admin.productos.create', 'uses' => 'ProductosController@create']);
            Route::post('registrar', ['as' => 'admin.productos.store', 'uses' => 'ProductosController@store']);
            Route::get('editar/{id}', ['as' => 'admin.productos.edit', 'uses' => 'ProductosController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.productos.update', 'uses' => 'ProductosController@update']);
            Route::get('eliminar/{id}', ['as' => 'admin.productos.delete', 'uses' => 'ProductosController@delete']);
        });

        Route::group(['prefix' => 'servicios'], function() {
            Route::get('/', ['as' => 'admin.servicios.index', 'uses' => 'ServiciosController@index']);
            Route::get('registrar', ['as' => 'admin.servicios.create', 'uses' => 'ServiciosController@create']);
            Route::post('registrar', ['as' => 'admin.servicios.store', 'uses' => 'ServiciosController@store']);
            Route::get('editar/{id}', ['as' => 'admin.servicios.edit', 'uses' => 'ServiciosController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.servicios.update', 'uses' => 'ServiciosController@update']);
            Route::get('eliminar/{id}', ['as' => 'admin.servicios.delete', 'uses' => 'ServiciosController@delete']);
        });

        Route::group(['prefix' => 'cursos'], function() {
            Route::get('/', ['as' => 'admin.cursos.index', 'uses' => 'CursosController@index']);
            Route::get('registrar', ['as' => 'admin.cursos.create', 'uses' => 'CursosController@create']);
            Route::post('registrar', ['as' => 'admin.cursos.store', 'uses' => 'CursosController@store']);
            Route::get('editar/{id}', ['as' => 'admin.cursos.edit', 'uses' => 'CursosController@edit']);
            Route::post('editar/{id}', ['as' => 'admin.cursos.update', 'uses' => 'CursosController@update']);

app/InvoiceManual.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class InvoiceManual extends Model
{
    protected $fillable = [
        'header',
        'number',
        'invoice_date',
        'due_date',
        'id_user',
        'user_data',
    ];

    protected $dates = [
        'invoice_date',
        'due_date',
    ];

    public function getTotalAttribute()
    {
        return $this->items->reduce(function($a, $b) {
            return $a + $b->amount;
        }, 0);
    }

    public function usuario()
    {
        return $this->belongsTo(User::class, 'id_user', 'id');
    }

    public function items()
    {
        return $this->hasMany(ItemInvoiceManual::class, 'id_invoice', 'id');
    }

    public function scopeFiltrar($q, Request $request)
    {
        if ($request->has('usuario')) {
            $q = $q->where('id_user', '=', $request->usuario);
        }

        return $q;
    }
}

app/Http/Controllers/Admin/InvoiceManualController.php
<?php

namespace App\Http\Controllers\Admin;

use App\InvoiceManual;
use App\ItemInvoiceManual;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class InvoiceManualController extends Controller
{
    public function index(Request $request)
    {
        $invoices = InvoiceManual::orderBy('created_at', 'desc')
            ->filtrar($request)
            ->paginate(20);
        return view('admin.invoice-manual.index', [
            'invoices' => $invoices,
            'usuarios' => $this->getUsuarios(),
            'usuario' => $request->usuario,
        ]);
    }

    public function getUserData(Request $request)
    {
        $invoice = InvoiceManual::select('user_data')->orderBy('created_at', 'desc')
            ->filtrar($request)
            ->first();
        return !is_null($invoice) ? $invoice->user_data : '';
    }

    public function create()
    {
        $last = InvoiceManual::orderBy('created_at', 'desc')->first();
        return view('admin.invoice-manual.create', [
            'usuarios' => $this->getUsuarios(false),
            'now' => Carbon::today()->toDateString(),
            'last' => $last
        ]);
    }

    public function store(Request $request)
    {
        $allOk = false;
        $invoice = null;
        $index = -1;
        $items = array_map(function ($item) use ($request, &$index) {
            $index++;
            return [
                'item' => $item,
                'description' => $request->description[$index],
                'price' => $request->price[$index],
                'quantity' => $request->quantity[$index],
                'amount' => $request->amount[$index],
            ];
        }, $request->item);
        $items = array_filter($items, function ($item) {
            return !is_null($item['description']) != '' && $item['description'];
        });
        if (count($items) === 0) {
            return redirect()->back()->withErrors('Es obligatorio crear items');
        }
        DB::transaction(function () use ($request, $items, &$allOk, &$invoice) {
            $invoice = InvoiceManual::create($request->all());
            foreach ($items as $item) {
                ItemInvoiceManual::create([
                    'id_invoice' => $invoice->id,
                    'item' => $item['item'],
                    'description' => $item['description'],
                    'price' => $item['price'],
                    'quantity' => $item['quantity'],
                    'amount' => $item['amount'],
                ]);
            }
            $allOk = true;
        });
        if (!$allOk) {
            return redirect()->back()->withInput()->withErrors('Hubo un error al procesar la transacción, intente de nuevo');
        }
        return redirect()->route('admin.invoice-manual.show', [$invoice->id])->with([
            'msg' => 'Invoice creado con éxito'
        ]);
    }

    public function show($id)
    {
        $invoice = InvoiceManual::find($id);
        return view('admin.invoice-manual.show', [
            'invoice' => $invoice
        ]);
    }

    public function printView($id)
    {
        $invoice = InvoiceManual::find($id);
        return view('admin.invoice-manual.print-view', [
            'invoice' => $invoice
        ]);
    }

    private function getUsuarios($acceptAll = true)
    {
        $res = [];
        if ($acceptAll) {
            $res[''] = "----TODOS LOS USUARIOS----";
        }
        foreach(User::select('id', 'name', 'last_name')->where('type', '=', 2)->get() as $usuario) {
            $res[$usuario->id] = $usuario->id . ' - ' . $usuario->full_name;
        }
        return $res;
    }
}

resources/views/admin/invoice-manual/index.blade.php
@extends('admin.master')
@section('titulo-pagina', 'Invoices')
@section('contenido')
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="header">
                    {!! Form::open(['route' => 'admin.invoice-manual.index', 'method' => 'GET']) !!}
                        <div class="form-group">
                            <label for="usuario">Filtrar por usuario</label>
                            {!! Form::select('usuario', $usuarios, $usuario, ['class' => 'form-control selectpicker', 'data-live-search' => 'true']) !!}
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Filtrar</button>
                            <a href="{{ route('admin.invoice-manual.create') }}" class="btn btn-primary">Registrar invoice</a>
                        </div>
                    {!! Form::close() !!}
                </div>
                <div class="content">
                    <table class="table table-full-width table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Nombre del usuario</th>
                            <th>Total</th>
                            <th>Fecha de creación</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($invoices as $invoice)
                            <tr>
                                <td>{{ $invoice->id }}</td>
                                <td>{{ $invoice->usuario->full_name }}</td>
                                <td>US$ {{ $invoice->total }}</td>
                                <td>{{ $invoice->created_at->format('d/m/Y H:i') }}</td>
                                <td>
                                    <a href="{{ route('admin.invoice-manual.show', [$invoice->id]) }}" class="btn btn-info">
                                        <i class="fa fa-eye"></i> Ver Invoice
                                    </a>
                                    <a href="{{ route('admin.invoice-manual.print-view', [$invoice->id]) }}" class="btn btn-info">
                                        <i class="fa fa-print"></i> Imprimir Invoice
                                    </a>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="footer">
                    {!! $invoices->appends(request()->input())->render() !!}
                </div>
            </div>
        </div>
    </div>
@stop
@section('css')
    <link rel="stylesheet" href="{{ url('css/bootstrap-select.min.css') }}">
    <style>
        .tracking-list {
            list-style-type: none;
        }
    </style>
@endsection
@section('js')
    <script src="{{ url('js/bootstrap-select.min.js') }}"></script>
@endsection

resources/views/admin/invoice-manual/print-view.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Imprimir Invoice Manual #{{ $invoice->number }}</title>
    <link href="{{ url('vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
</head>
<body>
    <div class="container-fluid">

        <div class="row top">
            <div class="col-md-6 col-print-6">
                <div style="height: 100px;">{!! nl2br($invoice->header) !!}</div>
                <div>
                    {!! $invoice->usuario->full_name !!} <br>
                    {!! nl2br($invoice->user_data) !!}
                </div>
            </div>
            <div class="col-md-6 col-print-6 text-right">
                <img src="{{ url('assets/img/logo-strbox.png') }}" alt="StrBox" style="height: 130px; margin: 10px 0;">
                <h1>INVOICE</h1>
                <div class="row">
                    <div class="col-md-6 col-print-6">
                        <strong>Invoice #</strong>
                    </div>
                    <div class="col-md-6 col-print-6">{{ $invoice->number }}</div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-print-6">
                        <strong>Invoice Date</strong>
                    </div>
                    <div class="col-md-6 col-print-6">{{ $invoice->invoice_date->format('d/m/Y') }}</div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-print-6">
                        <strong>Due Date</strong>
                    </div>
                    <div class="col-md-6 col-print-6">{{ $invoice->due_date->format('d/m/Y') }}</div>
                </div>

            </div>
        </div>

        <div class="row" id="invoice">
            <table class="table">
                <thead class="gray-bg">
                <tr>
                    <th>Item</th>
                    <th>Description</th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Amount</th>
                </tr>
                </thead>
                <tbody>
                @foreach($invoice->items as $item)
                    <tr>
                        <td>{{ $item->item }}</td>
                        <td>{{ $item->description }}</td>
                        <td>{{ number_format($item->price, 2) }}</td>
                        <td>{{ number_format($item->quantity, 2) }}</td>
                        <td>{{ number_format($item->amount, 2) }}</td>
                    </tr>
                @endforeach
                <tr class="limit">
                    <td colspan="2"></td>
                    <td colspan="3" class="totales">
                        <div class="row">
                            <div class="col-md-6 col-print-6 text-left">
                                <strong>Subtotal</strong>
                            </div>
                            <div class="col-md-6 col-print-6 text-right">{{ number_format($invoice->total, 2) }}</div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td colspan="3" class="limit totales">
                        <div class="row">
                            <div class="col-md-6 col-print-6 text-left">
                                <strong>Total</strong>
                            </div>
                            <div class="col-md-6 col-print-6 text-right">{{ number_format($invoice->total, 2) }}</div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td colspan="3" class="totales">
                        <div class="row">
                            <div class="col-md-6 col-print-6 text-left">
                                <strong>Amount Paid</strong>
                            </div>
                            <div class="col-md-6 col-print-6 text-right">{{ number_format(0, 2) }}</div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td colspan="3" class="limit totales gray-bg">
                        <div class="row">
                            <div class="col-md-6 col-print-6 text-left">
                                <strong>Balance Due</strong>
                            </div>
                            <div class="col-md-6 col-print-6 text-right">${{ number_format($invoice->total, 2) }}</div>
                        </div>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>

    </div>

    <style>
        #invoice table {
            border: 1px solid #000000;
        }

        #invoice .table>tbody>tr>td {
            border: 0;
        }

        #invoice .table>thead>tr>th {
            border-bottom: 1px solid #000;
        }

        .gray-bg {
            background-color: #d3d3d3!important;
            -webkit-print-color-adjust: exact;
        }

        .limit {
            border-top: 1px solid #000000!important;
        }

        .totales {
            border-left: 1px solid #000000!important;
        }

        .top {
            margin-bottom: 50px;
        }

        /* BOOTSTRAP */
        .col-print-1 {width:8%;  float:left;}
        .col-print-2 {width:16%; float:left;}
        .col-print-3 {width:25%; float:left;}
        .col-print-4 {width:33%; float:left;}
        .col-print-5 {width:42%; float:left;}
        .col-print-6 {width:50%; float:left;}
        .col-print-7 {width:58%; float:left;}
        .col-print-8 {width:66%; float:left;}
        .col-print-9 {width:75%; float:left;}
        .col-print-10{width:83%; float:left;}
        .col-print-11{width:92%; float:left;}
        .col-print-12{width:100%; float:left;}

    </style>

    <script>
        window.print();
    </script>
</body>
</html>

resources/views/admin/invoice-manual/show.blade.php
@extends('admin.master')
@section('titulo-pagina', 'Invoice #' . $invoice->id)
@section('contenido')
    <div class="row">
        <div class="col-md-12" style="width: 100%">
            <div class="x_panel">
                <div class="content">

                    <div class="row">
                        <div class="col-md-6">
                            <div style="height: 100px;">{!! nl2br($invoice->header) !!}</div>
                            <div>
                                {!! $invoice->usuario->full_name !!} <br>
                                {!! nl2br($invoice->user_data) !!}
                            </div>
                        </div>
                        <div class="col-md-6 text-right">
                            <img src="{{ url('assets/img/logo-strbox.png') }}" alt="StrBox" style="height: 130px; margin: 10px 0;">
                            <h1>INVOICE</h1>
                            <div class="row">
                                <div class="col-md-6">
                                    <strong>Invoice #</strong>
                                </div>
                                <div class="col-md-6">{{ $invoice->number }}</div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <strong>Invoice Date</strong>
                                </div>
                                <div class="col-md-6">{{ $invoice->invoice_date->format('d/m/Y') }}</div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <strong>Due Date</strong>
                                </div>
                                <div class="col-md-6">{{ $invoice->due_date->format('d/m/Y') }}</div>
                            </div>

                        </div>
                    </div>

                    <div class="row">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Item</th>
                                <th>Description</th>
                                <th>Unit Price</th>
                                <th>Quantity</th>
                                <th>Amount</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($invoice->items as $item)
                                <tr>
                                    <td>{{ $item->item }}</td>
                                    <td>{{ $item->description }}</td>
                                    <td>{{ number_format($item->price, 2) }}</td>
                                    <td>{{ number_format($item->quantity, 2) }}</td>
                                    <td>{{ number_format($item->amount, 2) }}</td>
                                </tr>
                            @endforeach
                            <tr>
                                <td colspan="2"></td>
                                <td colspan="3">
                                    <div class="row">
                                        <div class="col-md-6 text-left">
                                            <strong>Subtotal</strong>
                                        </div>
                                        <div class="col-md-6 text-right">{{ number_format($invoice->total, 2) }}</div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2"></td>
                                <td colspan="3">
                                    <div class="row">
                                        <div class="col-md-6 text-left">
                                            <strong>Total</strong>
                                        </div>
                                        <div class="col-md-6 text-right">{{ number_format($invoice->total, 2) }}</div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2"></td>
                                <td colspan="3">
                                    <div class="row">
                                        <div class="col-md-6 text-left">
                                            <strong>Amount Paid</strong>
                                        </div>
                                        <div class="col-md-6 text-right">0</div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2"></td>
                                <td colspan="3">
                                    <div class="row">
                                        <div class="col-md-6 text-left">
                                            <strong>Balance Due</strong>
                                        </div>
                                        <div class="col-md-6 text-right">${{ number_format($invoice->total, 2) }}</div>
                                    </div>
                                </td>
                            </tr>

                            </tbody>
                        </table>
                    </div>

                    <div class="row">
                        <a href="{{ route('admin.invoice-manual.print-view', [$invoice->id]) }}" class="btn btn-primary">Imprimir</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
@stop
@section('css')
    <style>
        #invoice {
            margin: 20px;
            font-family: sans-serif;
        }

        #invoice .invoice-logo {
            text-align: center;
            background-color: #211973;
        }

        #invoice .invoice-header {
            padding: 20px;
            text-align: right;
        }

        #invoice .invoice-table {
            width: 95%;
            margin: 0 auto;
            border-collapse: collapse
        }

        #invoice .invoice-table thead {
            border-bottom: 2px solid #aaa;
        }

        #invoice .invoice-table thead th {
            text-align: center;
        }

        #invoice .invoice-table tbody tr {
            border-top: solid 1px #ddd; text-align: center;
        }
        
        #invoice .invoice-table tbody td {
            padding: 12px 0;
        }

        #invoice .invoice-footer {
            padding-bottom: 20px;
            text-align: right;
        }

        .signature {
            display: none;
            border-top: 1px solid #000000;
            padding: 15px 80px;
            text-align: left;
        }

        @media print {
            .nav_menu, footer, .print {
                display: none;
            }

            .signature {
                display: inline;
            }
        }
    </style>
@endsection